package com.netflix.spinnaker.keel.api.artifacts

/**
 * The build metadata of an artifact.
 */
data class BuildMetadata(
  val id: Int, // should be converted to number. Needs to be removed
  val number: String? = null, // build number, currently duplicate value to id
  val uid: String? = null, // a unique id for the build, which is generated by the CI service
  val jobUrl: String? = null,
  val jobName: String? = null,
  val completedAt: String? = null,
  val startedAt: String? = null
)
