language: java
jdk:
- openjdk8
sudo: required
dist: trusty
install: gradle/installViaTravis.sh
script: gradle/buildViaTravis.sh
before_cache: gradle/prepCaches.sh
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: Pe1RIdGZAa2uUl/1bdbphFlfs1KmIPbirABLPXGUwEwDDhyj5yJQg0PgVPhN1HAZS3fKR3LMHf7kt60Luu28Fxy3K3V+jlTkKRgjGwKCZZm28b6HurIpaZsSVdzTFpsne8L+8Yg0lyt0qsBgvDT6C1yD185npxm+cagXlPZzJK6JSZAcK+0HL5CJA4R2vCUGgLZPyby2Yx0zOg+uQffdGLDcbIFV8rhfjzjE1b0XS4ph3Q6K5ZWp/Hqj6hCrEbIApowcf7qVR1RGAV+9l56aZk/DAkfC9wiUvObXafpi3HXlGweB/9zIH8+yIGsqHwIODZvbFHgp2UXct4ao0A+1kXzt/Bbz0wQHIfohUcCi/i9r7mJiY83LBRFvonelYF5w7pyVSQWedzz4EcqLom/kbLJ5k3so7YW9MMFUTCutajpArtwICcL+VwjK04ZdyvNCQ3d1VaE8GnyiDR3K+ibSktdq0Oe5ivjrmb+lfcitfelbAJW0jjk7MSfish7T5bv79N9WOXwmXkkKaElYyZ28Etz4CwaMO8qltQd6Y+TBggGxT6wMwb0g/su7hvYDd1ckIUUPg6nBT1UxSmjpfGnMbtYHy+eI1XOEGNqFyHb6PinDT54djqmNAX5mJswPDH1JdfvlNlJ5ZrRcCadgvc7rDxYYiTCznqFsX5/Otmb9/Ds=
  - secure: Q+eofsbpUrAUHgSOrE7QhmmOmd9ueMq8rS7W7zOVklFud2HMP/4FEe5wy7rr0ikRMyQ98IRU1ioKZ85e9eayPP5DTRkQAhOCfO9p2dvxS7BBodW/uo6D2XLt4NPKOURmLIM8JHSeU2hI3DFTny/8Q4AyyG+4HFFZ5LEQsh5FR1qcJgY/wHDcIV/vlvUzR5/dwXT2fBAc0zgVzFT9H0FFkjBoWbkUyum9eVznWDF22mtcg33KQVG0zD92lJxbM66JLMKR/v/lNXz/503yWOtG0zd+sNWXF6SVtFlZe9LaP5f9xaNp+TafBymeo1biy+b6C1+shOVOUxqDOW8FWG1rL12TqDZSzmWmTKprR/RU6i586bcPLOh4sgYjRRmcOUQ/LdgrRxq0YzY+2YA0YGJYyuXvJw0nAehIcvElqUcbk5R/3R6D90Hxsjzo1EX4Q6z6H0ogMMes0josOaKcGbPFXrl4Sfp/omBAlQ3labtLU3y8yzdxwwgLdhqOsOZ8Wp8wRhMF8QHQ9KlLm2gijdN9mFjFH+Tk/JDbKN8RlM8uK2H9UUA3OECBIZA3qt5sPWUR7MtRyj5BgzGDXyo0JpVzwLLOwKCeM5DnyD7pV5hWA3MhU30mlKpv0BmokXwYX2NyLg6OjbKslXIT5AOQiF7vlkb6EhCTM3PSq7HDNQwd8IE=
