FROM alpine:3.11
MAINTAINER sig-platform@spinnaker.io
RUN apk --no-cache add --update bash openjdk8-jre
RUN adduser -D -S spinnaker
COPY keel-web/build/install/keel-web /opt/keel
RUN mkdir -p /opt/keel/plugins && chown -R spinnaker:nogroup /opt/keel/plugins
USER spinnaker
CMD ["/opt/keel/bin/keel-web"]
