FROM ubuntu:bionic
MAINTAINER sig-platform@spinnaker.io
RUN apt-get update && apt-get -y install openjdk-8-jre-headless wget
RUN adduser --disabled-login --system spinnaker
COPY keel-web/build/install/keel-web /opt/keel
RUN mkdir -p /opt/keel/plugins && chown -R spinnaker:nogroup /opt/keel/plugins
USER spinnaker
CMD ["/opt/keel/bin/keel-web"]
