databaseChangeLog:
  - changeSet:
      id: add-status-to-environment-artifact-versions
      author: fletch
      changes:
        - addColumn:
            tableName: environment_artifact_versions
            columns:
              - column:
                  name: status
                  type: varchar(255)
                  constraints:
                    nullable: false
      rollback:
        - dropColumn:
            tableName: environment_artifact_versions
            columnName: status
