databaseChangeLog:
- changeSet:
    id: service-account-on-delivery-config
    author: fletch
    changes:
    - addColumn:
        tableName: delivery_config
        columns:
        - column:
            name: service_account
            type: varchar(255)
            constraints:
              nullable: false
    rollback:
    - dropColumn:
        tableName: delivery_config
        columnName: service_account
