databaseChangeLog:
- changeSet:
    id: fix-environment-resource-pk
    author: fletch
    changes:
    - dropPrimaryKey:
        tableName: environment_resource
    - addPrimaryKey:
        tableName: environment_resource
        columnNames: environment_uid, environment_version, resource_uid
