databaseChangeLog:
  - changeSet:
      id: create-preview-environment-table
      author: lpollo
      changes:
        - createTable:
            tableName: preview_environment
            columns:
              - column:
                  name: delivery_config_uid
                  type: char(26)
                  constraints:
                    primaryKey: true
                    foreignKeyName: fk_preview_environment_delivery_config
                    referencedTableName: delivery_config
                    referencedColumnNames: uid
                    deleteCascade: true
              - column:
                  name: base_environment_uid
                  type: char(26)
                  constraints:
                    primaryKey: true
                    foreignKeyName: fk_preview_environment_environment
                    referencedTableName: environment
                    referencedColumnNames: uid
                    deleteCascade: true
              - column:
                  name: branch_filter
                  type: json
                  constraints:
                    nullable: false
              - column:
                  name: verifications
                  type: json
                  constraints:
                    nullable: true
              - column:
                  name: notifications
                  type: json
                  constraints:
                    nullable: true
