databaseChangeLog:
  - changeSet:
      id: add-raw-delivery-config
      author: rhorev
      changes:
        - addColumn:
            tableName: delivery_config
            columns:
              - column:
                  name: raw_config
                  type: longtext
