databaseChangeLog:
- changeSet:
    id: latest-environment-view
    author: fletch
    changes:
    - createView:
        viewName: latest_environment
        selectQuery: |
          select uid, delivery_config_uid, name, max(version) as version, constraints, notifications, verifications
          from environment, environment_version
          where environment.uid = environment_version.environment_uid
          group by environment.uid
