databaseChangeLog:
  - changeSet:
      id: delivery-config-updated-at
      author: rhorev
      changes:
        - addColumn:
            tableName: delivery_config
            columns:
              - name: updated_at
                type: timestamp(3)
                afterColumn: api_version
