databaseChangeLog:
- changeSet:
    id: last-resource-check-status
    author: fletch
    changes:
    - renameColumn:
        tableName: task_tracking
        oldColumnName: timestamp
        newColumnName: started_at
        columnDataType: datetime(3)
    - addColumn:
        tableName: task_tracking
        columns:
        - column:
            name: status
            type: varchar(64)
            afterColumn: subject
            constraints:
            - nullable: false
            value: RUNNING
        - column:
            name: resource_id
            type: varchar(255)
            afterColumn: subject
            constraints:
            - nullable: true
        - column:
            name: environment_name
            type: varchar(255)
            afterColumn: subject
            constraints:
            - nullable: true
        - column:
            name: application
            type: varchar(255)
            afterColumn: subject
            constraints:
            - nullable: true
        - column:
            name: subject_type
            type: varchar(64)
            afterColumn: subject
            constraints:
            - nullable: true
        - column:
            name: ended_at
            type: datetime(3)
            afterColumn: started_at
            constraints:
            - nullable: true
    - sql:
        sql: |
          update task_tracking
          set subject_type = substring_index(subject, ':', 1);
    - sql:
        sql: |
          update task_tracking
          set resource_id = substring_index(task_tracking.subject, ':', -4)
          where subject like 'RESOURCE:%';
    - sql:
        sql: |
          update task_tracking
          set environment_name = (
            select active_environment.name
            from active_environment
            join environment_resource
            on active_environment.uid = environment_resource.environment_uid
            and active_environment.version = environment_resource.environment_version
            join active_resource
            on active_resource.uid = environment_resource.resource_uid
            and active_resource.metadata->>'$.version' = environment_resource.resource_version
            where active_resource.id = task_tracking.resource_id
          )
          where resource_id is not null;
    - sql:
        sql: |
          update task_tracking
          set application = (select application from resource where id = task_tracking.resource_id)
          where resource_id is not null;
    - addNotNullConstraint:
        tableName: task_tracking
        columnName: application
        columnDataType: varchar(255)
    - addNotNullConstraint:
        tableName: task_tracking
        columnName: subject_type
        columnDataType: varchar(64)
    - dropColumn:
        tableName: task_tracking
        columnName: subject
    - createIndex:
        tableName: task_tracking
        columns:
        - column:
            name: ended_at
        indexName: task_tracking_ended_at_idx
    - createIndex:
        tableName: task_tracking
        columns:
        - column:
            name: application
        - column:
            name: environment_name
        - column:
            name: resource_id
        indexName: task_tracking_application_environment_resource_idx
